name: flutter_storage_fileio
description: A simple expense tracker app built with Flutter.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Consider '>=3.0.0 <4.0.0' if all packages support it

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9       # optional: store user profile / pet
  lottie: ^3.1.0
  google_sign_in: ^6.2.1   # if you wire up Google login
  flutter_secure_storage: ^9.0.0  # store tokens securely
  font_awesome_flutter: ^10.7.0        # ⬅ add this
  audioplayers: ^6.0.0
  http: ^1.2.1 # Or any later compatible version (e.g., ^1.1.0, ^1.2.0)

  # Core packages
  path_provider: ^2.1.3 # Check pub.dev for the absolute latest stable version
  cupertino_icons: ^1.0.8

  # Game feature (Flame)
  flame: ^1.17.0 # Check pub.dev for latest

  flutter_dotenv: ^5.1.0 # Add this line


  # Internationalisation
  intl: ^0.20.2 # This is fairly recent, but double check

  # Charting
  fl_chart: ^0.71.0 # Check pub.dev for latest

  # 📷 Camera preview & capture
  camera: ^0.11.0+1 # Check pub.dev for latest

  # 🤖 On-device text-recognition via ML Kit
  google_mlkit_text_recognition: ^0.15.0 # This seems fairly recent, but double check

  # AR Plugin
  ar_flutter_plugin_2: ^0.0.3
  vector_math: ^2.1.4 # Usually kept in sync with Flutter SDK

  # PDF Generation and Printing/Sharing
  pdf: ^3.10.8          # Added for PDF creation (or latest from pub.dev)
  printing: ^5.11.1     # Added for PDF layout/sharing (or latest from pub.dev)
  # open_filex: ^4.4.0  # Optional: if you want to directly open the PDF after saving (or latest)


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Check pub.dev for latest
  flutter_launcher_icons: ^0.14.4 # Added for app icon generation

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg_room.png
    - assets/images/e_pet_idle_sheet_horizontal.png
    - assets/images/e_pet_hungry.png
    - assets/images/e_pet_cry.png
    - assets/images/google_logo.png
    - assets/images/apple_logo.png
    - assets/images/3d_ar_pet.glb
    - assets/images/Astronaut.glb # Make sure this file actually exists in this path if you intend to load it locally
    - assets/audio/e_pet_bgmusic.mp3 # Make sure this file actually exists in this path if you intend to load it locally
    # Note: You DO NOT need to add "assets/icon/e_pet_apps_icon.jpg" here.
    # The flutter_launcher_icons package handles the icon path from its own configuration.
    # NEW – lottie files
    - assets/animations/pet_idle.json
    - assets/animations/pet_error.json

    # mascot for sign‑up page
    - assets/animations/egg_idle.json
    # Alternatively, to include all files in the images directory:
    # - assets/images/

# Configuration for flutter_launcher_icons
# Make sure this section is at the root level of the pubspec.yaml (same indentation as 'name', 'dependencies', etc.)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/e_pet_apps_icon.png"
  # Optional: if you want to specify an adaptive icon background color for Android (Oreo+)
  # adaptive_icon_background: "#FFFFFF"
  # Optional: if you want to specify a foreground image for adaptive icons (Android Oreo+)
  # This is useful if your main icon is not suitable for the foreground layer of an adaptive icon.
  # adaptive_icon_foreground: "assets/icon/e_pet_apps_icon_foreground.png"

