// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNlw1aZl1OkZ18wZieZ9i18HkhZS1I6u4',
    appId: '1:995637601021:web:1362d52b0f700d51c61494',
    messagingSenderId: '995637601021',
    projectId: 'accountingapp-fe504',
    authDomain: 'accountingapp-fe504.firebaseapp.com',
    storageBucket: 'accountingapp-fe504.firebasestorage.app',
    measurementId: 'G-8SFL0725QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFYqegaAmU7FSsaDAWnR94lAqg2aUyE0M',
    appId: '1:995637601021:android:db4cb29683e18971c61494',
    messagingSenderId: '995637601021',
    projectId: 'accountingapp-fe504',
    storageBucket: 'accountingapp-fe504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB1tj9JetXAReH7fFR7kiE_-0ySdkK1GA',
    appId: '1:995637601021:ios:2cf4279eab6a30bdc61494',
    messagingSenderId: '995637601021',
    projectId: 'accountingapp-fe504',
    storageBucket: 'accountingapp-fe504.firebasestorage.app',
    iosBundleId: 'com.example.accountingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB1tj9JetXAReH7fFR7kiE_-0ySdkK1GA',
    appId: '1:995637601021:ios:2cf4279eab6a30bdc61494',
    messagingSenderId: '995637601021',
    projectId: 'accountingapp-fe504',
    storageBucket: 'accountingapp-fe504.firebasestorage.app',
    iosBundleId: 'com.example.accountingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNlw1aZl1OkZ18wZieZ9i18HkhZS1I6u4',
    appId: '1:995637601021:web:648395d20527a638c61494',
    messagingSenderId: '995637601021',
    projectId: 'accountingapp-fe504',
    authDomain: 'accountingapp-fe504.firebaseapp.com',
    storageBucket: 'accountingapp-fe504.firebasestorage.app',
    measurementId: 'G-G766135TXF',
  );

}